### ISSUE TITLE
Request for a matrix multiplication operation

### ISSUE THREAD

**Issue by nsfox** [LTLA/beachmat#28]
Request for multiplying two matrices together. For example, multiplying a matrix in memory (ex. a weights matrix) by a DelayedArray (ex. a matrix of genomic tiles).

**Comment by LTLA** [comment]
It is done (02f5abfe1baf5904cad257fd5b261e82c4accd10). Also note the additional `tatami.*` methods that allow you to do a lot of extra stuff without having to operate on the original matrix.
