### ISSUE TITLE
Missing header `tatami_r/parallelize.hpp`

### ISSUE THREAD

**Issue by grimbough** [LTLA/beachmat#30]
Hi @LTLA 

I'm currently seeing the following error when trying to install the devel version of **BiocSingular**.  I think the issue is here with  your recent updates to **beachmat**.

<pre>&gt; BiocManager::install(&apos;BiocSingular&apos;)

Bioconductor version 3.20 (BiocManager 1.30.24), R 4.4.1 (2024-06-14)
Installing package(s) &apos;BiocSingular&apos;
trying URL &apos;https://bioconductor.org/packages/3.20/bioc/src/contrib/BiocSingular_1.21.2.tar.gz&apos;
Content type &apos;application/x-gzip&apos; length 617772 bytes (603 KB)
==================================================
downloaded 603 KB

* installing *source* package ‘BiocSingular’ ...
** package ‘BiocSingular’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
using C++17
g++ -std=gnu++17 -I&quot;/usr/local/lib/R/include&quot; -DNDEBUG  -I&apos;/usr/local/lib/R/site-library/Rcpp/include&apos; -I&apos;/usr/local/lib/R/site-library/beachmat/include&apos; -I/usr/local/include    -fpic  -g -O2 -fstack-protector-strong -Wformat -Wformat-security -Wdate-time -D_FORTIFY_SOURCE=2 -g   -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I&quot;/usr/local/lib/R/include&quot; -DNDEBUG  -I&apos;/usr/local/lib/R/site-library/Rcpp/include&apos; -I&apos;/usr/local/lib/R/site-library/beachmat/include&apos; -I/usr/local/include    -fpic  -g -O2 -fstack-protector-strong -Wformat -Wformat-security -Wdate-time -D_FORTIFY_SOURCE=2 -g   -c compute_scale.cpp -o compute_scale.o
In file included from <b>compute_scale.cpp:1</b>:
<b>/usr/local/lib/R/site-library/beachmat/include/Rtatami.h:6:10:</b> <font color="#EF2929"><b>fatal error: </b></font>tatami_r/parallelize.hpp: No such file or directory
    6 | #include <font color="#EF2929"><b>&quot;tatami_r/parallelize.hpp&quot;</b></font>
      |          <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
compilation terminated.
make: *** [/usr/local/lib/R/etc/Makeconf:204: compute_scale.o] Error 1
ERROR: compilation failed for package ‘BiocSingular’
</pre>

**Comment by LTLA** [comment]
This was fixed a while ago, BioC-devel just hasn't propagated the version bump yet.

**Comment by grimbough** [comment]
Perfect, all fixed now.
